#pragma once
#include "samd11.h"

#define SMARTAG_I2C_SERCOM                  SERCOM0
#define SMARTAG_I2C_SERCOM_GCLK_ID_CORE     SERCOM0_GCLK_ID_CORE
#define SMARTAG_I2C_SERCOM_GCLK_ID_SLOW     SERCOM0_GCLK_ID_SLOW
#define SMARTAG_I2C_SERCOM_APBCMASK_BIT     PM_APBCMASK_SERCOM0

// I2C pin mux: PA08 = SDA (PAD2), PA09 = SCL (PAD3)
#define SMARTAG_I2C_SDA_PINMUX              PINMUX_PA08D_SERCOM0_PAD2
#define SMARTAG_I2C_SCL_PINMUX              PINMUX_PA09D_SERCOM0_PAD3