#pragma once
#include "samd11.h"

#define SMARTAG_I2C_SERCOM                  SERCOM0
#define SMARTAG_I2C_SERCOM_GCLK_ID_CORE     SERCOM0_GCLK_ID_CORE
#define SMARTAG_I2C_SERCOM_GCLK_ID_SLOW     SERCOM0_GCLK_ID_SLOW
#define SMARTAG_I2C_SERCOM_APBCMASK_BIT     PM_APBCMASK_SERCOM0

#define SMARTAG_I2C_SDA_PINMUX              PINMUX_PA04D_SERCOM0_PAD0
#define SMARTAG_I2C_SCL_PINMUX              PINMUX_PA07C_SERCOM0_PAD1